default: &default
  adapter: postgresql
  host: <%= ENV.fetch("CI_DATABASE", "0.0.0.0") %>
  port: 5432
  username: postgres
  password: super_secret_password__DO_NOT_STEAL
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
  url: <%= ENV['DATABASE_URL']
  password: <%= ENV['RAILS_DATABASE_PASSWORD'] %>
