variables:
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: super_secret_password__DO_NOT_STEAL
  CI_DATABASE: postgres

cache:
  key: "$CI_COMMIT_REF_NAME"

image: maxjohansen/volkano

stages:
  - Code climate
  - Unit tests
  - End to end tests
  - Reporting

rubocop:
  stage: Code climate
  tags:
    - ci-alpine-latest
  script:
    - rubocop -R backend

jest:
  stage: Unit tests
  tags:
    - ci-alpine-latest
  script:
    - cd frontend
    - yarn install
    - yarn ci
  artifacts:
    paths:
      - frontend/coverage/

rspec:
  stage: Unit tests
  tags:
    - ci-alpine-latest
  services:
    - postgres:alpine
  script:
    - cd backend
    - bundle install --jobs $(nproc) --path=../gems
    - bundle exec rspec
  artifacts:
    paths:
      - backend/coverage/

coverage:
  stage: Reporting
  tags:
    - ci-alpine-latest
  dependencies:
    - rspec
    - jest
  script:
    - cat backend/coverage/index.html | grep -oP '(\d+\.\d+)%\</span\>' | head -n 1 | cut -d% -f1
    - cat frontend/coverage/lcov-report/index.html | grep -B 1 'Lines' | grep -oP '(\d+\.\d+)% \</span\>' | cut -d% -f1

# cypress:
#   stage: End to end tests
#   cache:
#     paths:
#       - backend/gems
#       - frontend/node_modules
#   tags:
#     - ci-alpine-latest
#   artifacts:
#     when: on_failure
#     paths:
#       - frontend/cypress/screenshots/
#       - frontend/cypress/videos/
#   services:
#     - postgres:alpine
#   script:
#     - cd backend
#     - bundle install --jobs $(nproc) --path=gems
#     - bundle exec rails db:setup
#     - bundle exec rails s & > /dev/null
#     - cd ../frontend
#     - yarn install
#     - yarn dev & > /dev/null
#     - yarn cyprun
