variables:
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: super_secret_password__DO_NOT_STEAL
  CI_DATABASE: postgres

cache:
  key: "$CI_COMMIT_REF_NAME"

image: maxjohansen/volkano

stages:
  - Code climate
  - Unit tests
  - End to end tests
  - Coverage

rubocop:
  stage: Code climate
  tags:
    - ci-alpine-latest
  script:
    - rubocop -R backend

jest:
  stage: Unit tests
  tags:
    - ci-alpine-latest
  script:
    - cd frontend
    - yarn install
    - yarn quicktest

rspec:
  stage: Unit tests
  tags:
    - ci-alpine-latest
  services:
    - postgres:alpine
  script:
    - cd backend
    - bundle install --jobs $(nproc) --path=../gems
    - bundle exec rspec

# cypress:
#   stage: End to end tests
#   cache:
#     paths:
#       - backend/gems
#       - frontend/node_modules
#   tags:
#     - ci-alpine-latest
#   artifacts:
#     when: on_failure
#     paths:
#       - frontend/cypress/screenshots/
#       - frontend/cypress/videos/
#   services:
#     - postgres:alpine
#   script:
#     - cd backend
#     - bundle install --jobs $(nproc) --path=gems
#     - bundle exec rails db:setup
#     - bundle exec rails s & > /dev/null
#     - cd ../frontend
#     - yarn install
#     - yarn dev & > /dev/null
#     - yarn cyprun
