variables:
  POSTGRES_DB: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: super_secret_password__DO_NOT_STEAL
  CI_DATABASE: postgres

image: maxjohansen/volkano

stages:
  - Code climate
  - Unit tests
  - End to end tests
  - Reporting
  - Deploy

rubocop:
  stage: Code climate
  tags:
    - ci-alpine-latest
  script:
    - rubocop -R backend

jest:
  stage: Unit tests
  tags:
    - ci-alpine-latest
  cache:
    key: dependencies
    policy: push
    paths:
      - frontend/node_modules
  script:
    - cd frontend
    - yarn install
    - yarn ci
  artifacts:
    paths:
      - frontend/coverage/

rspec:
  stage: Unit tests
  tags:
    - ci-alpine-latest
  services:
    - postgres:alpine
  cache:
    key: dependencies
    policy: push
    paths:
      - backend/.bundle
      - gems
  script:
    - cd backend
    - bundle install --jobs $(nproc) --path=../gems
    - bundle exec rspec
  artifacts:
    paths:
      - backend/coverage/

coverage:
  stage: Reporting
  tags:
    - ci-alpine-latest
  dependencies:
    - rspec
    - jest
  script:
    - ./report_coverage.sh

cypress:
  stage: End to end tests
  tags:
    - ci-alpine-latest
  artifacts:
    when: on_failure
    paths:
      - frontend/cypress/screenshots/
      - frontend/cypress/videos/
  services:
    - postgres:alpine
  variables:
    DATABASE_URL: postgres://postgres:super_secret_password__DO_NOT_STEAL@postgres:5432
    RAILS_ENV: production
  cache:
    key: dependencies
    policy: pull
    paths:
      - frontend/node_modules
      - backend/.bundle
      - gems
  script:
    - cd backend
    - bundle install --jobs $(nproc) --path=../gems
    - bundle exec rails db:create db:migrate db:seed
    - bundle exec rails s &
    - cd ../frontend
    - yarn install
    - PORT=3000 yarn start &
    - yarn cyprun

staging:
  type: Deploy
  tags:
    - ci-alpine-latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=volkano-staging --api-key=$HEROKU_API_KEY
    - dpl --provider=heroku --app=volkano-staging-api --api-key=$HEROKU_API_KEY
  only:
    - development

production:
  type: Deploy
  tags:
    - ci-alpine-latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=volkano --api-key=$HEROKU_API_KEY
    - dpl --provider=heroku --app=volkano-api --api-key=$HEROKU_API_KEY
  only:
    - master
