AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'gems/**/*'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A\s*#']

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'Guardfile'

Style/Documentation:
  Exclude:
    - '**/*'
