AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A\s*#']

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - '**/*'
